### PR TITLE
feature: add mute functionality

### PR DESCRIPTION
**Pull request by gokaygurcan**
- Also fix format errors and add XO as linter

---

I know it's huge, but I'll try my best to explain if necessary. Good luck!

Best,
G.

### CODE REVIEW

**Comment by gokaygurcan** [comment]
Hi,
After this one, I'm planning to work on a CI tool such as Travis, and avoiding display to turn off. I checked night shift, but I couldn't find a way other than opening the system preferences and changing it.

And I know some people who are waiting for the mute functionality. No pressure, just saying. 

Best,
G.

**Comment by zehfernandes** [comment]
Hi @gokaygurcan 

Nice contribution. Thanks to added a lint to the project. It's important :)

About the mute functionality. I think you can use the mute instead of `volume 0`.  That way we preserve the user volume without the need to reset to 100 after toggle pliim.

```
set volume with output muted
set volume without output muted
```

What do you think? Can you make this change?

**Comment by gokaygurcan** [comment]
Hey @zehfernandes,
It's even better, pushing in a minute.

**Comment by zehfernandes** [comment]
Thanks @gokaygurcan 🎉

I merged with master and committed a new label.
 https://github.com/zehfernandes/pliim/commit/8d6b7a97a3eb4e8d86486f5e5c8374b7d131e7fa

**Comment by gokaygurcan** [comment]
Hooraay!

**Pull request merged**
